kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.volume.metadata.name }}
spec:
  storageClassName: {{ .Values.volume.spec.storageClassName }}
  capacity:
    storage: {{ .Values.volume.spec.capacity.storage }}
  accessModes:
    - ReadWriteOnce
  local:
    path: {{ .Values.volume.spec.local.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.node }}

