kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.volumeClaim.metadata.name }}
spec:
  storageClassName: {{ .Values.volume.spec.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumeClaim.spec.resources.requests.storage }}
