apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
  - image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 1;done"]
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
