volume:
  metadata:
    name: elasticsearch-pv
  spec:
    storageClassName: elasticsearch-storage-class
    capacity:
      storage: 10Gi
    hostPath:
      path: '/mnt/elasticsearch-volume'
    accessModes:
      - ReadWriteOnce

volumeClaim:
  metadata:
    name: elasticsearch-pvc
  spec:
    resources:
      requests:
        storage: 10Gi
